### ISSUE TITLE
Scanner dysfunctional

### ISSUE THREAD

**Issue by Maestro04** [webhintio/webhint.io#916] opened 2020-07-08 06:49 UTC
Chrome Version : 79.0.3945.117 (Official Build) (64-bit)
OS : Linux
JavaScript : V8 7.9.317.32
URL : https://freequote.safestyle-windows.co.uk/composite-doors.php
**Steps To Reproduce** :
1) Open https://webhint.io/scanner/
2) Paste the URL in the text box 'Enter your URL here'
3) Click on 'RUN SCAN'
**Message Displayed** : Uh-oh! There's been an error and the scan could not start.

**Comment by DanielRuf** [comment] 2020-07-08 06:51
Wanted to report the same. Here is some additional information about this:

![grafik](https://user-images.githubusercontent.com/827205/86886968-24cc1b80-c0f8-11ea-9050-79828bf6ccac.png)

**Comment by sarvaje** [comment] 2020-07-08 16:45
@Maestro04 @DanielRuf thanks for open the issue. I'm going to work on it.

**Comment by sarvaje** [comment] 2020-07-09 20:09
@Maestro04 @DanielRuf the scanner should be working fine.

I'm going to close the issue. Please, feel free to reopen it if you still have the issue.

**Closed by sarvaje** 2020-07-09 20:09 UTC
Labels: msft-consider

**Comment by DanielRuf** [comment] 2020-07-09 20:18
Thanks, the scanner seems to work again now.

What was the cause and how was it resolved?

**Comment by sarvaje** [comment] 2020-07-09 20:24
for some reason, the azure functions in production were empty. I also took advantage on the "under construction" status and I improved the deployment to production, so next time we have an issue, at least the deployment should be very straight forward jejeje

**Comment by sarvaje** [comment] 2020-07-09 20:25
I didn't mention it, but the scanner runs on Azure functions hehehe

**Comment by DanielRuf** [comment] 2020-07-09 21:18
Awesome, thanks for the technical and interesting explanation and taking care of these things.

**Comment by sarvaje** [comment] 2020-07-09 21:25
Thank you for reporting the issue! :)
